package com.citi.spellingBee.util;


public enum ContentStatus {
	NEW, 
	WORD_CORRECTED_BY_WORDSMITH , 
	WORD_APPROVED_BY_REVIEWER,  
	WORD_REJECTED_BY_REVIEWER,  
	PRONUNCIATION_APPROVED_BY_REVIEWER, 
	PRONUNCIATION_REJECTED_BY_REVIEWER,
	PRONUNCIATION_RECORDED
}
